### ISSUE TITLE
Is it possible to get a video guide how to install OpenWrt on Xiaomi Router AC1200 RB02 router?

### ISSUE THREAD

**Issue by Maneeha1234SL** [Ser9ei/xiaomi-r4agv2-openwrt_patch#1]
Is it possible to get a video guide how to install OpenWrt on Xiaomi Router AC1200 RB02 router?

**Comment by Ser9ei** [comment]
> Is it possible to get a video guide how to install OpenWrt on Xiaomi Router AC1200 RB02 router?

Try solution by link below
https://github.com/acecilia/OpenWRTInvasion/issues/141#issuecomment-1296033775
